interface Window {
           attribute DOMString label;
           attribute boolean defaultSelected;
};

interface Window {
           attribute DOMString label;
           attribute boolean defaultSelected;
};

interface DOMStringMap {
  getter DOMString (DOMString name);
  setter creator void (DOMString name, DOMString value);
  deleter void (DOMString name);
};